<?php 
namespace Starter\Theme;

if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly.
}

class Starter_Theme {

    /**
     * Initialize the theme
     */
    public static function init() {
        self::define_constants();
        self::includes();
        
        add_action( 'after_setup_theme', [ __CLASS__, 'theme_setup' ] );
        add_action( 'wp_enqueue_scripts', [ __CLASS__, 'enqueue_assets' ], 20 );
        add_action( 'enqueue_block_editor_assets', [ __CLASS__, 'enqueue_editor_assets' ], 20 );
        
        add_filter( 'upload_mimes', [ __CLASS__, 'allow_svg_upload' ] );

        // Initialize ACF helpers if included
        if ( class_exists( __NAMESPACE__ . '\\Starter_ACF_JSON' ) && method_exists( __NAMESPACE__ . '\\Starter_ACF_JSON', 'init' ) ) {
            \Starter\Theme\Starter_ACF_JSON::init();
        }
        if ( class_exists( __NAMESPACE__ . '\\Starter_ACF_Blocks' ) && method_exists( __NAMESPACE__ . '\\Starter_ACF_Blocks', 'init' ) ) {
            \Starter\Theme\Starter_ACF_Blocks::init();
        }
    }

    /**
     * Define theme constants
     */
    public static function define_constants() {
        if ( ! defined( 'ST_THEME_VERSION' ) ) {
            define( 'ST_THEME_VERSION', '0.1.0' );
        }
        if ( ! defined( 'ST_THEME_NAME' ) ) {
            $theme = wp_get_theme();
            define( 'ST_THEME_NAME', $theme->get( 'Name' ) ? $theme->get( 'Name' ) : 'Starter Theme' );
        }
        if ( ! defined( 'ST_TEXT_DOMAIN' ) ) {
            define( 'ST_TEXT_DOMAIN', 'st-starter' );
        }
        if ( ! defined( 'ST_COMPANY_NAME' ) ) {
            define( 'ST_COMPANY_NAME', 'Nombre de la empresa' );
        }
        if ( ! defined( 'ST_API_GOOGLE_MAPS' ) ) {
            define( 'ST_API_GOOGLE_MAPS', 'YOUR_API_KEY' );
        }
        if ( ! defined( 'VITE_DEV_SERVER_PORT' ) ) {
            define( 'VITE_DEV_SERVER_PORT', '5173' );  // Default Vite port
        }

    }

    /**
     * Include necessary files
     */
    public static function includes() {
        $files = [
            'inc/class-assets.php',
            'inc/class-acf-json.php',
            'inc/class-acf-blocks.php',
        ];
        foreach ( $files as $file ) {
            $path = get_template_directory() . '/' . $file;
            if ( file_exists( $path ) ) {
                require_once $path;
            }
        }
    }

    /**
     * Setup theme features
     */
    public static function theme_setup() {
        // Make theme available for translation
        load_theme_textdomain( ST_TEXT_DOMAIN, get_template_directory() . '/languages' );

        // Basic theme supports
        add_theme_support( 'automatic-feed-links' );
        add_theme_support( 'title-tag' );
        add_theme_support( 'post-thumbnails' );
        add_theme_support( 'html5', array( 'search-form', 'gallery', 'caption', 'comment-form' ) );
        add_theme_support( 'post-formats', array( 'aside', 'image', 'video', 'quote', 'link', 'audio', 'gallery', 'status' ) );
        add_theme_support( 'custom-logo' );
        add_theme_support( 'custom-background' );

        // Editor styles
        add_theme_support( 'editor-styles' );
        add_editor_style([
            'assets/css/editor.css'
        ]);

        // Block and widget supports
        add_theme_support( 'wp-block-styles' );
        add_theme_support( 'widgets-block-editor' );
        add_theme_support( 'align-wide' );
        add_theme_support( 'responsive-embeds' );

        // WooCommerce
        add_theme_support( 'woocommerce' );
    }

    /**
     * Enqueue theme assets
     */
    public static function enqueue_assets() {
        // Bootstrap CSS from CDN
        wp_enqueue_style( 
            'bootstrap',
            'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css',
            [],
            '5.3.3'
        );

        // Enqueue fonts and main styles
        wp_enqueue_style(
            'st-starter-fonts',
            get_theme_file_uri('/assets/css/fonts.css'),
            ['bootstrap'],
            ST_THEME_VERSION
        );

        // If Vite dev server is running, enqueue the module served by Vite.
        if ( self::is_dev_server() ) {
            // Vite serves module at /assets/js/main.js according to your config
            $dev_url = self::get_vite_dev_url() . '/assets/js/main.js';
            wp_register_script( 'st-vite-dev-main', $dev_url, [], null );
            wp_script_add_data( 'st-vite-dev-main', 'type', 'module' );
            wp_enqueue_script( 'st-vite-dev-main' );

            // Vite injects CSS in dev automatically, so do not enqueue main.css here.
            return;
        }

        // Production: try to read manifest.json generated by Vite build
        $manifest = self::get_manifest();
        if ( $manifest ) {
            // The manifest key is the input path used in rollup (e.g. "assets/js/main.js")
            $entry_key = 'assets/js/main.js';
            if ( isset( $manifest[ $entry_key ] ) ) {
                $entry = $manifest[ $entry_key ];

                // Enqueue JS
                if ( ! empty( $entry['file'] ) ) {
                    $js_url = get_stylesheet_directory_uri() . '/dist/' . ltrim( $entry['file'], '/' );
                    $ver = file_exists( get_stylesheet_directory() . '/dist/' . $entry['file'] ) ? filemtime( get_stylesheet_directory() . '/dist/' . $entry['file'] ) : ST_THEME_VERSION;
                    wp_enqueue_script( 'st-main', $js_url, [], $ver, true );
                }

                // Enqueue any CSS that the manifest lists for this entry
                if ( ! empty( $entry['css'] ) && is_array( $entry['css'] ) ) {
                    foreach ( $entry['css'] as $css_file ) {
                        $css_url = get_stylesheet_directory_uri() . '/dist/' . ltrim( $css_file, '/' );
                        $css_ver = file_exists( get_stylesheet_directory() . '/dist/' . $css_file ) ? filemtime( get_stylesheet_directory() . '/dist/' . $css_file ) : ST_THEME_VERSION;
                        wp_enqueue_style( 'st-' . sanitize_title( $css_file ), $css_url, [], $css_ver );
                    }
                }
                return;
            }
        }

        // Fallback: enqueue compiled assets directly from theme (non-hashed)
        wp_enqueue_style(
            'st-starter-main',
            get_stylesheet_directory_uri() . '/assets/css/main.css',
            [ 'st-starter-fonts' ],
            ST_THEME_VERSION
        );

        wp_enqueue_script(
            'st-starter-script',
            get_stylesheet_directory_uri() . '/assets/js/main.js',
            [],
            ST_THEME_VERSION,
            true
        );
    }

    /**
     * Enqueue editor (Gutenberg) assets (dev or prod)
     */
    public static function enqueue_editor_assets() {
        // If dev server is running, use Vite editor entry
        if ( self::is_dev_server() ) {
            $dev_url = self::get_vite_dev_url() . '/assets/js/editor.js';
            wp_register_script( 'st-vite-dev-editor', $dev_url, [], null );
            wp_script_add_data( 'st-vite-dev-editor', 'type', 'module' );
            wp_enqueue_script( 'st-vite-dev-editor' );

            // Vite injects editor CSS in dev
            return;
        }

        // Production: read manifest and enqueue editor assets if present
        $manifest = self::get_manifest();
        if ( $manifest ) {
            $entry_key = 'assets/js/editor.js';
            if ( isset( $manifest[ $entry_key ] ) ) {
                $entry = $manifest[ $entry_key ];

                if ( ! empty( $entry['file'] ) ) {
                    $js_url = get_stylesheet_directory_uri() . '/dist/' . ltrim( $entry['file'], '/' );
                    $ver = file_exists( get_stylesheet_directory() . '/dist/' . $entry['file'] ) ? filemtime( get_stylesheet_directory() . '/dist/' . $entry['file'] ) : ST_THEME_VERSION;
                    wp_enqueue_script( 'st-editor', $js_url, [], $ver, true );
                }

                if ( ! empty( $entry['css'] ) && is_array( $entry['css'] ) ) {
                    foreach ( $entry['css'] as $css_file ) {
                        $css_url = get_stylesheet_directory_uri() . '/dist/' . ltrim( $css_file, '/' );
                        $css_ver = file_exists( get_stylesheet_directory() . '/dist/' . $css_file ) ? filemtime( get_stylesheet_directory() . '/dist/' . $css_file ) : ST_THEME_VERSION;
                        wp_enqueue_style( 'st-editor-' . sanitize_title( $css_file ), $css_url, [], $css_ver );
                    }
                }
                return;
            }
        }

        // Fallback editor CSS/JS (non-hashed)
        wp_enqueue_style( 'st-starter-editor', get_stylesheet_directory_uri() . '/assets/css/editor.css', [], ST_THEME_VERSION );
        wp_enqueue_script( 'st-starter-editor-script', get_stylesheet_directory_uri() . '/assets/js/editor.js', [ 'wp-blocks', 'wp-dom-ready', 'wp-edit-post' ], ST_THEME_VERSION, true );
    }

    /**
     * Get Vite dev server URL (read from constant or fallback)
     *
     * @return string
     */
    protected static function get_vite_dev_url(): string {
        if ( defined( 'VITE_DEV_SERVER_PORT' ) && filter_var( VITE_DEV_SERVER_PORT, FILTER_VALIDATE_URL ) ) {
            return rtrim( 'http://localhost:' . VITE_DEV_SERVER_PORT, '/' );
        }

        return 'http://localhost:5173'; // Default fallback
    }


    /**
     * Check if Vite dev server is running (quick HEAD request)
     *
     * @param int $port
     * @return bool
     */
    public static function is_dev_server( $timeout = 0.5 ): bool {
        $url = self::get_vite_dev_url() . '/';
        $args = [
            'timeout'     => $timeout,
            'redirection' => 0,
            'httpversion' => '1.1',
        ];
        $response = wp_remote_head( $url, $args );
        if ( is_wp_error( $response ) ) {
            return false;
        }
        $code = wp_remote_retrieve_response_code( $response );
        return (int) $code === 200;
    }

    /**
     * Read and parse Vite manifest.json (cached statically during the request)
     *
     * @return array|null
     */
    protected static function get_manifest() {
        static $manifest = null;
        if ( $manifest !== null ) {
            return $manifest;
        }
        $manifest_path = get_stylesheet_directory() . '/dist/manifest.json';
        if ( ! file_exists( $manifest_path ) ) {
            $manifest = null;
            return null;
        }
        $json = file_get_contents( $manifest_path );
        $manifest = json_decode( $json, true );
        return $manifest;
    }

    /**
     * Allow SVG file uploads (simple, no sanitization)
     */
    public static function allow_svg_upload( $mimes ) {
        $mimes['svg'] = 'image/svg+xml';
        return $mimes;
    }
}